---
title: "ProtestVZLA"
author: "ZMRS"
date: "4/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Library
```{r}
library(readr)
library(ggplot2)
library(tseries)
```


## Add data
```{r}
monthlyprotest <- read_csv("data/monthlyprotest.csv", 
    col_types = cols(Date = col_date(format = "%m/%d/%Y")))
View(monthlyprotest)
```
## Time series
##View data
```{r}
Protests <- ts(monthlyprotest$Protests, start = 2011, frequency = 12)
plot.ts(Protests)

##Yearly mean plot
plot.ts(aggregate(Protests, FUN= mean), ylab = "Protests")
```

## Plot by month, year replicates

```{r}

boxplot(monthlyprotest$Protests~ordered(monthlyprotest$Month, levels = c("January","February","March","April","May","June","July","August","September","October","November","December")),
        xlab = "Months",
        ylab = "Protests in Venezuela")

```

## Stationary data test

```{r}
adf.test(diff(log(Protests)), alternative="stationary",k=0)
```

## ACF and PACF plot
```{r}
acf(log(Protests),main="",col="red")
acf(diff(log(Protests)),main="",col="red")
pacf(diff(log(Protests)),main="",col="red")
```

## Decomposition of time series

```{r}
#With log or without log?
ProtDecomp <- decompose(Protests)
plot(ProtDecomp)
```

## Selecting the model
```{r}
# AR order
model10 <- arima(Protests,order=c(1,0,0))
model20 <- arima(Protests,order=c(2,0,0))
model30 <- arima(Protests,order=c(3,0,0))
model40 <- arima(Protests,order=c(4,0,0))
model50 <- arima(Protests,order=c(5,0,0))
model60 <- arima(Protests,order=c(6,0,0))
AIC(model10,model20,model30,model40,model50,model60)
#degree of differencing
model01 <- arima(Protests,order=c(0,0,1))
model02 <- arima(Protests,order=c(0,0,2))
model03 <- arima(Protests,order=c(0,0,3))
model04 <- arima(Protests,order=c(0,0,4))
model05 <- arima(Protests,order=c(0,0,5))
model06 <- arima(Protests,order=c(0,0,6))
AIC(model01,model02,model03,model04,model05,model06)

##both
model10 <- arima(Protests,order=c(1,0,0))
model11 <- arima(Protests,order=c(1,0,1))
model12 <- arima(Protests,order=c(1,0,2))
model13 <- arima(Protests,order=c(1,0,3))
AIC(model10,model11,model12,model13)
#MA order
model100 <- arima(Protests,order=c(1,0,2))
model101 <- arima(Protests,order=c(1,1,2))
model102 <- arima(Protests,order=c(1,2,2))
model103 <- arima(Protests,order=c(1,3,2))
AIC(model100,model101,model102,model103)
```



## ARIMA model
```{r}
fit <- arima(log(Protests), c(1,1,2), seasonal = list(order = c(1,1,2), period = 12))
pred <- predict(fit, n.ahead = 10*12)
ts.plot(Protests,2.718^pred$pred, log="y", lty = c(1,3), ylab = "Protests in Venezuela")
```


